import { AgentIconEntry, ServerIconEntry } from "./icons-utils";

/**
 * kind: "base"
 *   Iconify `logos` set. e.g. key "slack" → logos:slack
 *   withIcon: 'true' means that a `logos:<key>-icon` icon also exists and both UIs prefer this when available.
 *
 * kind: "custom"
 *   The icon lives in a different Iconify set or its ID contains chars that don't
 *   match the registry key.
 *   color is optional if we want to better adjust the icon.
 *
 * kind: "local"
 *   No Iconify icon exists for this server.
 *   mcpx-ui skips the network check and return /icons/<key>.png directly.
 *   admin-ui fall back to the MCP default icon.
 */
export const SERVER_ICON_REGISTRY: Record<string, ServerIconEntry> = {
  airtable: { kind: "base" },
  appdynamics: { kind: "base" },
  apolloio: { kind: "local" },
  asana: { kind: "base", withIcon: true },
  atlassian: { kind: "base" },
  aws: { kind: "base" },
  azuredevops: {
    kind: "custom",
    iconifyId: "simple-icons:azuredevops",
    color: "#0078D7",
  },
  bamboohr: {
    kind: "custom",
    iconifyId: "arcticons:bamboohr",
    color: "#599D15",
  },
  basecamp: { kind: "base" },
  bitbucket: { kind: "base" },
  brave: { kind: "base" },
  circleci: { kind: "base" },
  clickhouse: { kind: "custom", iconifyId: "devicon:clickhouse" },
  clickup: {
    kind: "custom",
    iconifyId: "simple-icons:clickup",
    color: "#7B68EE",
  },
  cloudflare: { kind: "base", withIcon: true },
  coda: { kind: "base", withIcon: true },
  context7: { kind: "custom", iconifyId: "vscode-icons:file-type-context7" },
  coralogix: { kind: "local" },
  datadog: { kind: "base" },
  discord: { kind: "base", withIcon: true },
  docker: { kind: "base", withIcon: true },
  doppler: { kind: "local" },
  elastic: { kind: "custom", iconifyId: "logos:elasticsearch" },
  fathom: { kind: "local" },
  figma: { kind: "base" },
  github: { kind: "base", withIcon: true },
  gitlab: { kind: "base", withIcon: true },
  gmail: { kind: "custom", iconifyId: "logos:google-gmail" },
  google: { kind: "custom", iconifyId: "devicon:google" },
  googleanalytics: { kind: "custom", iconifyId: "logos:google-analytics" },
  googlemeet: { kind: "custom", iconifyId: "logos:google-meet" },
  gotomeeting: {
    kind: "custom",
    iconifyId: "simple-icons:gotomeeting",
    color: "#F68D2E",
  },
  grafana: { kind: "base" },
  harbor: { kind: "custom", iconifyId: "simple-icons:harbor" },
  hashicorpvault: { kind: "custom", iconifyId: "logos:hashicorp" },
  hubspot: {
    kind: "custom",
    iconifyId: "simple-icons:hubspot",
    color: "#f8761f",
  },
  jenkins: { kind: "base" },
  jira: { kind: "base" },
  kubernetes: { kind: "base" },
  launchdarkly: { kind: "base", withIcon: true },
  linear: { kind: "base", withIcon: true },
  loadmill: { kind: "local" },
  microsoftdynamics: {
    kind: "custom",
    iconifyId: "simple-icons:dynamics365",
    color: "#0B53CE",
  },
  microsoftteams: { kind: "custom", iconifyId: "logos:microsoft-teams" },
  monday: { kind: "base", withIcon: true },
  n8n: { kind: "custom", iconifyId: "simple-icons:n8n", color: "#EA4B71" },
  newrelic: { kind: "custom", iconifyId: "logos:new-relic-icon" },
  notion: { kind: "base", withIcon: true },
  pipedrive: { kind: "base" },
  playwright: { kind: "base" },
  postgres: { kind: "custom", iconifyId: "logos:postgresql" },
  postgresql: { kind: "base" },
  prometheus: { kind: "base" },
  puppeteer: { kind: "base" },
  "qa-envtest": {
    kind: "custom",
    iconifyId: "hugeicons:test-tube-01",
    color: "#5147E4",
  },
  redis: { kind: "custom", iconifyId: "simple-icons:redis", color: "#c6302b" },
  rollbar: {
    kind: "custom",
    iconifyId: "simple-icons:rollbar",
    color: "#EC4A28",
  },
  salesforce: { kind: "base" },
  sentry: { kind: "base", withIcon: true },
  slack: { kind: "base", withIcon: true },
  snowflake: { kind: "base", withIcon: true },
  sourceforge: {
    kind: "custom",
    iconifyId: "simple-icons:sourceforge",
    color: "#FF6600",
  },
  splunk: { kind: "base" },
  terraform: { kind: "base", withIcon: true },
  time: { kind: "custom", iconifyId: "hugeicons:time-02" },
  travisci: {
    kind: "custom",
    iconifyId: "simple-icons:travisci",
    color: "#3EAAAF",
  },
  trello: { kind: "base" },
  webex: { kind: "custom", iconifyId: "simple-icons:webex" },
  zoho: { kind: "custom", iconifyId: "simple-icons:zoho", color: "#E42527" },
  zoom: { kind: "base", withIcon: true },
};

export const AGENT_ICON_REGISTRY: Record<string, AgentIconEntry> = {
  anthropic: { kind: "custom", iconifyId: "logos:claude-icon" },
  chatgpt: { kind: "custom", iconifyId: "simple-icons:openai" },
  claude: { kind: "custom", iconifyId: "logos:claude-icon" },
  claudedesktop: { kind: "custom", iconifyId: "logos:claude-icon" },
  claudecode: {
    kind: "custom",
    iconifyId: "cbi:claude-clawd",
    color: "#d97757",
  },
  codex: { kind: "local" },
  copilot: { kind: "custom", iconifyId: "logos:github-copilot" },
  cursor: { kind: "custom", iconifyId: "simple-icons:cursor" },
  default: {
    kind: "custom",
    iconifyId: "hugeicons:mcp-server",
    color: "#5147E4",
  },
  geminicli: { kind: "local" },
  inspector: {
    kind: "custom",
    iconifyId: "hugeicons:mcp-server",
    color: "#5147E4",
  },
  lunarorbiter: {
    kind: "custom",
    iconifyId: "majesticons:planet-rocket-line",
    color: "#5147E4",
  },
  n8n: { kind: "custom", iconifyId: "simple-icons:n8n", color: "#EA4B71" },
  openai: { kind: "custom", iconifyId: "simple-icons:openai" },
  "openai-mcp": { kind: "custom", iconifyId: "simple-icons:openai" },
  "visual studio code": {
    kind: "custom",
    iconifyId: "logos:visual-studio-code",
  },
  opencode: { kind: "custom", iconifyId: "simple-icons:opencode" },
  vscode: { kind: "custom", iconifyId: "logos:visual-studio-code" },
  warp: { kind: "custom", iconifyId: "simple-icons:warp" },
  windsurf: {
    kind: "custom",
    iconifyId: "simple-icons:windsurf",
    color: "#00BFA5",
  },
};
export const MCP_ICON_COLORS: string[] = [
  "#6CC2CE",
  "#3563E0",
  "#464CB0",
  "#8C409E",
  "#E5421F",
  "#019894",
  "#551EE0",
  "#50E3C2",
  "#FF77A9",
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#96CEB4",
  "#FFEAA7",
  "#DDA0DD",
  "#98D8C8",
  "#F7DC6F",
  "#82E0AA",
  "#D7BDE2",
  "#F0B27A",
  "#85C1E9",
  "#F1948A",
  "#73C6B6",
  "#E59866",
  "#7FB3D8",
  "#C39BD3",
  "#7DCEA0",
  "#F0E68C",
  "#87CEEB",
  "#DDA0DD",
  "#B0E0E6",
  "#FFB6C1",
  "#EC972A",
  "#90EE90",
  "#FFA07A",
  "#ADD8E6",
  "#FFE4B5",
  "#98FB98",
  "#DEB887",
  "#AFEEEE",
  "#FFDAB9",
  "#B0C4DE",
  "#FFE4E1",
  "#8FBC8F",
  "#D2B48C",
  "#66CDAA",
  "#BC8F8F",
  "#5F9EA0",
  "#DAA520",
  "#CD853F",
  "#6B8E23",
  "#708090",
];
