apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-proxy.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "lunar-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.serviceMonitor.port }}
      targetPort: 3000
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.healthCheckPort }}
      targetPort: 8040
      protocol: TCP
      name: healthcheck
    - port: {{ .Values.service.adminPort }}
      targetPort: 8081
      protocol: TCP
      name: admin
  selector: {{- include "lunar-proxy.selectorLabels" . | nindent 4 }}
