version: "3.8"

services:
  oauth-mock:
    image: node:22-alpine
    working_dir: /app
    volumes:
      # Mount the built OAuth server from testkit-mcp-server
      - ../../testkit-mcp-server/dist:/app
      # Mount node_modules for dependencies
      - ../../testkit-mcp-server/node_modules:/app/node_modules
    command: node oauth-mock.js
    ports:
      - "9001:9001"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9001/status"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 2s
