version: "3.8"
services:
  httpbinmock:
    image: kennethreitz/httpbin:latest
    ports:
      - "80:80"

  mox:
    image: eliavlavi/mox-server:0.5.2
    ports:
      - "9898:9898"

  logic-mock-server:
    build:
      context: .
      dockerfile: Dockerfile.logic-mock-server
    ports:
      - "9000:9000"

  client:
    build:
      context: ${INTERCEPTOR_DIR}
      dockerfile: test-client/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LUNAR_HANDSHAKE_PORT
      - LUNAR_PROXY_HOST
      - LUNAR_ALLOW_LIST
      - LUNAR_BLOCK_LIST
      - LUNAR_FILTER_BY_HEADER
      - LUNAR_ENTER_COOLDOWN_AFTER_ATTEMPTS=1
      - LUNAR_EXIT_COOLDOWN_AFTER_SEC=2
      - LUNAR_INTERCEPTOR_LOG_LEVEL=DEBUG
    depends_on:
      - httpbinmock
      - logic-mock-server
